sonar.projectKey=medlink
sonar.projectName=medlink
sonar.host.url=http://localhost:9000
sonar.token=squ_d7e55bf16b9a793bb2d188d59631818b54022a3b

sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/build/**,**/coverage/**,**/*.test.*,**/*.spec.*