sonar.projectKey=medlink
sonar.projectName=medlink
sonar.host.url=http://localhost:9000

sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/build/**,**/coverage/**,**/*.test.*,**/*.spec.*