export type WorkflowStep = {
  title: string;
  desc: string;
  icon: string;
  role?: string; // who acts at this step
};

export type DeptWorkflow = {
  slug: string;
  name: string;
  tagline: string;
  color: string;          // tailwind gradient classes
  accentBg: string;       // light bg class
  accentText: string;     // text color class
  accentBorder: string;
  conditions: string[];
  steps: WorkflowStep[];
  specialists: string[];
  tests: string[];
  bookDept: string;       // matches /appointment?dept= value
};

export const workflows: DeptWorkflow[] = [
  {
    slug: "cardiology",
    name: "Cardiology",
    tagline: "Heart & Vascular Care",
    color: "from-rose-500 to-red-600",
    accentBg: "bg-rose-50",
    accentText: "text-rose-700",
    accentBorder: "border-rose-200",
    conditions: ["Chest pain & discomfort", "High blood pressure", "Heart disease & failure", "Arrhythmia", "Coronary artery disease", "Valve disorders"],
    specialists: ["Cardiologist", "Cardiac Surgeon", "Echocardiologist", "Electrophysiologist"],
    tests: ["ECG / EKG", "Echocardiogram (ECHO)", "Stress Test", "Holter Monitor", "Coronary Angiography", "Blood Lipid Panel"],
    bookDept: "Cardiology",
    steps: [
      { title: "Book Cardiology Appointment", desc: "Patient submits appointment request with symptoms — chest pain, BP issues, palpitations.", icon: "📅", role: "Patient" },
      { title: "Department Admin Review", desc: "Cardiology admin reviews request, checks urgency, and confirms slot.", icon: "🗂️", role: "Admin" },
      { title: "Assign Cardiologist", desc: "Admin assigns a specialist cardiologist based on availability and case complexity.", icon: "👨‍⚕️", role: "Admin" },
      { title: "Initial Consultation", desc: "Cardiologist reviews history, listens to heart, checks BP and pulse. Determines test requirements.", icon: "🩺", role: "Cardiologist" },
      { title: "ECG / ECHO Test Order", desc: "Doctor orders ECG, echocardiogram or other cardiac diagnostics via lab request.", icon: "💓", role: "Cardiologist" },
      { title: "Lab Processes & Uploads Reports", desc: "Lab technician runs tests, pathologist verifies results and uploads report to the system.", icon: "🔬", role: "Lab" },
      { title: "Doctor Reviews Results", desc: "Cardiologist reviews uploaded lab reports and diagnostic images.", icon: "📋", role: "Cardiologist" },
      { title: "Diagnosis & Prescription", desc: "Final diagnosis issued. Medications prescribed. Surgery or further treatment recommended if needed.", icon: "💊", role: "Cardiologist" },
      { title: "Pharmacy Dispenses Medicines", desc: "Pharmacist verifies prescription, checks inventory and dispenses cardiac medications.", icon: "🏪", role: "Pharmacy" },
      { title: "Billing & Insurance", desc: "Invoice generated covering consultation, tests, medicines. Insurance deduction applied.", icon: "🧾", role: "Billing" },
      { title: "Follow-Up Scheduled", desc: "Next appointment booked. Patient instructed on diet, activity, and medication adherence.", icon: "📆", role: "Cardiologist" },
    ],
  },
  {
    slug: "neurology",
    name: "Neurology",
    tagline: "Brain, Spine & Nerve Care",
    color: "from-violet-500 to-purple-600",
    accentBg: "bg-violet-50",
    accentText: "text-violet-700",
    accentBorder: "border-violet-200",
    conditions: ["Migraine & chronic headaches", "Stroke & TIA", "Epilepsy & seizures", "Parkinson's disease", "Multiple sclerosis", "Memory & cognitive disorders"],
    specialists: ["Neurologist", "Neurosurgeon", "Epileptologist", "Stroke Specialist"],
    tests: ["MRI Brain", "CT Scan", "EEG", "Nerve Conduction Study (NCS)", "Lumbar Puncture", "Neuropsychological Testing"],
    bookDept: "Neurology",
    steps: [
      { title: "Book Neurology Appointment", desc: "Patient reports symptoms — migraines, seizures, numbness, weakness, memory loss.", icon: "📅", role: "Patient" },
      { title: "Neurology Admin Review", desc: "Admin assesses urgency (stroke cases prioritised), confirms slot.", icon: "🗂️", role: "Admin" },
      { title: "Assign Neurologist", desc: "Specialist assigned based on symptom type — epileptologist for seizures, stroke specialist for TIA/stroke.", icon: "🧠", role: "Admin" },
      { title: "Consultation", desc: "Neurologist performs detailed neurological exam — reflexes, cognition, coordination, sensory testing.", icon: "🩺", role: "Neurologist" },
      { title: "MRI / CT Scan Request", desc: "Imaging ordered to view brain and spinal cord structure for lesions, bleeds, or tumours.", icon: "🖥️", role: "Neurologist" },
      { title: "Lab Uploads Reports", desc: "Radiology tech performs scan, radiologist validates, report uploaded to patient file.", icon: "🔬", role: "Lab / Radiology" },
      { title: "Doctor Reviews Imaging", desc: "Neurologist carefully reviews MRI/CT images and correlates with clinical findings.", icon: "📋", role: "Neurologist" },
      { title: "Treatment Plan", desc: "Diagnosis confirmed. Medications prescribed. Physiotherapy, surgery or further specialist referral arranged.", icon: "💊", role: "Neurologist" },
      { title: "Pharmacy & Billing", desc: "Neurological medications dispensed. Full invoice generated, insurance processed.", icon: "🧾", role: "Pharmacy / Billing" },
      { title: "Follow-Up & Monitoring", desc: "Regular follow-ups to monitor neurological progress, adjust medications, review imaging.", icon: "📆", role: "Neurologist" },
    ],
  },
  {
    slug: "orthopedics",
    name: "Orthopedics",
    tagline: "Bone, Joint & Muscle Treatment",
    color: "from-amber-500 to-orange-600",
    accentBg: "bg-amber-50",
    accentText: "text-amber-700",
    accentBorder: "border-amber-200",
    conditions: ["Fractures & trauma", "Joint pain & stiffness", "Arthritis (OA/RA)", "Sports injuries", "Spine & disc disorders", "Tendon & ligament injuries"],
    specialists: ["Orthopedic Surgeon", "Joint Replacement Specialist", "Spine Surgeon", "Sports Medicine Doctor", "Physiotherapist"],
    tests: ["X-Ray", "MRI (soft tissue)", "CT Scan (complex fractures)", "Bone Density Scan (DEXA)", "Arthroscopy", "Blood Tests (ESR, CRP for arthritis)"],
    bookDept: "Orthopedics",
    steps: [
      { title: "Book Orthopedic Appointment", desc: "Patient presents with bone/joint pain, fracture, swelling, or limited mobility.", icon: "📅", role: "Patient" },
      { title: "Admin Review & Assignment", desc: "Admin reviews request and assigns orthopedic surgeon or specialist.", icon: "🗂️", role: "Admin" },
      { title: "Consultation & Examination", desc: "Doctor assesses range of motion, pain levels, swelling. Physical examination of affected area.", icon: "🩺", role: "Orthopedic Doctor" },
      { title: "X-Ray / Imaging Request", desc: "X-rays ordered for fractures. MRI for soft tissue. CT scan for complex bone injuries.", icon: "🦴", role: "Orthopedic Doctor" },
      { title: "Lab Processes & Uploads Report", desc: "Radiology performs imaging, technician uploads report and images to system.", icon: "🔬", role: "Lab / Radiology" },
      { title: "Diagnosis", desc: "Doctor reviews images to confirm fracture, arthritis grade, disc herniation, or ligament tear.", icon: "📋", role: "Orthopedic Doctor" },
      { title: "Physiotherapy or Surgery Recommendation", desc: "Conservative: physiotherapy, bracing, pain management. Surgical: fracture fixation, joint replacement, arthroscopy.", icon: "🏃", role: "Orthopedic Doctor" },
      { title: "Prescription & Medication", desc: "Pain medications, anti-inflammatories, calcium supplements prescribed. Physiotherapy sessions scheduled.", icon: "💊", role: "Orthopedic Doctor" },
      { title: "Pharmacy & Billing", desc: "Medicines dispensed. Full billing processed including any surgical/procedural costs.", icon: "🧾", role: "Pharmacy / Billing" },
      { title: "Physiotherapy & Follow-Up", desc: "Physiotherapy sessions tracked. Surgical cases monitored post-op. Progress imaging ordered as needed.", icon: "📆", role: "Doctor / Physio" },
    ],
  },
  {
    slug: "pediatrics",
    name: "Pediatrics",
    tagline: "Expert Children's Healthcare",
    color: "from-sky-500 to-blue-600",
    accentBg: "bg-sky-50",
    accentText: "text-sky-700",
    accentBorder: "border-sky-200",
    conditions: ["Fever & infections", "Growth & nutrition issues", "Vaccination & immunisation", "Respiratory issues (asthma, bronchitis)", "Neonatal care", "Child developmental delays"],
    specialists: ["Pediatrician", "Neonatologist", "Pediatric Surgeon", "Developmental Pediatrician"],
    tests: ["Blood Count (CBC)", "Urine Analysis", "Blood Culture", "Chest X-Ray", "Ultrasound (abdomen)", "Developmental Screening"],
    bookDept: "Pediatrics",
    steps: [
      { title: "Parent Books Pediatric Appointment", desc: "Parent/guardian books appointment on behalf of child, describes symptoms.", icon: "📅", role: "Parent / Guardian" },
      { title: "Admin Review & Assignment", desc: "Pediatrics admin confirms slot and assigns appropriate pediatrician.", icon: "🗂️", role: "Admin" },
      { title: "Consultation", desc: "Pediatrician examines child — weight, height, vitals, developmental milestones, symptom review.", icon: "🩺", role: "Pediatrician" },
      { title: "Lab Tests (if required)", desc: "Blood tests, urine culture, imaging ordered based on clinical findings.", icon: "🔬", role: "Pediatrician" },
      { title: "Vaccination Schedule", desc: "Immunisation history reviewed. Overdue vaccines administered. Next schedule planned.", icon: "💉", role: "Pediatrician / Nurse" },
      { title: "Lab Reports Uploaded", desc: "Lab technician processes tests. Results uploaded and linked to child's record.", icon: "📋", role: "Lab" },
      { title: "Diagnosis & Prescription", desc: "Doctor reviews results. Child-safe medications prescribed with dosage based on age and weight.", icon: "💊", role: "Pediatrician" },
      { title: "Growth Tracking Record", desc: "Height, weight, and BMI recorded in growth chart. Dietary advice given.", icon: "📈", role: "Pediatrician" },
      { title: "Pharmacy & Billing", desc: "Paediatric medications dispensed. Invoice generated, insurance applied.", icon: "🧾", role: "Pharmacy / Billing" },
      { title: "Follow-Up & Growth Monitoring", desc: "Next review scheduled. Parents given health education, dietary guidance, vaccination reminders.", icon: "📆", role: "Pediatrician" },
    ],
  },
  {
    slug: "dermatology",
    name: "Dermatology",
    tagline: "Skin, Hair & Nail Care",
    color: "from-pink-500 to-rose-500",
    accentBg: "bg-pink-50",
    accentText: "text-pink-700",
    accentBorder: "border-pink-200",
    conditions: ["Skin allergies & rashes", "Acne & comedones", "Hair loss & alopecia", "Eczema & psoriasis", "Fungal infections", "Skin cancer screening"],
    specialists: ["Dermatologist", "Cosmetic Dermatologist", "Dermatopathologist", "Trichologist (hair)"],
    tests: ["Skin Biopsy", "Patch Test (allergens)", "KOH Test (fungal)", "Dermoscopy", "Blood Tests (thyroid for hair loss)", "Skin Culture"],
    bookDept: "General Medicine",
    steps: [
      { title: "Book Dermatology Appointment", desc: "Patient describes skin, hair or nail symptoms. Photos can be submitted with the request.", icon: "📅", role: "Patient" },
      { title: "Admin Review & Assignment", desc: "Admin assigns a dermatologist. For cosmetic cases, cosmetic dermatologist assigned.", icon: "🗂️", role: "Admin" },
      { title: "Image Upload (Pre-Consultation)", desc: "Patient or staff uploads clinical photos of affected skin area for preliminary review.", icon: "📷", role: "Patient / Staff" },
      { title: "Consultation & Examination", desc: "Dermatologist examines skin under dermoscope, reviews medical history, allergies.", icon: "🩺", role: "Dermatologist" },
      { title: "Diagnostic Tests", desc: "Biopsy, patch tests, KOH scraping, or blood tests ordered based on diagnosis.", icon: "🔬", role: "Dermatologist" },
      { title: "Lab Processes & Uploads Reports", desc: "Skin samples processed, cultures grown, biopsy read by pathologist. Report uploaded.", icon: "📋", role: "Lab / Pathology" },
      { title: "Treatment Plan", desc: "Topical, systemic, or procedural treatment plan developed based on diagnosis.", icon: "📋", role: "Dermatologist" },
      { title: "Prescription", desc: "Topical creams, oral medications, or referral for cosmetic procedures prescribed.", icon: "💊", role: "Dermatologist" },
      { title: "Pharmacy & Billing", desc: "Dermatological medications dispensed. Invoice generated and insurance processed.", icon: "🧾", role: "Pharmacy / Billing" },
      { title: "Follow-Up", desc: "Progress review scheduled. Treatment response evaluated. Maintenance plan set.", icon: "📆", role: "Dermatologist" },
    ],
  },
  {
    slug: "general-medicine",
    name: "General Medicine",
    tagline: "Primary & Routine Healthcare",
    color: "from-teal-500 to-cyan-600",
    accentBg: "bg-teal-50",
    accentText: "text-teal-700",
    accentBorder: "border-teal-200",
    conditions: ["Fever & flu", "Bacterial & viral infections", "Routine health checkups", "Diabetes management", "Hypertension", "General wellness & preventive care"],
    specialists: ["General Physician (GP)", "Internal Medicine Doctor", "Diabetologist", "Geriatrician"],
    tests: ["Complete Blood Count (CBC)", "Blood Sugar (FBS/RBS/HbA1c)", "Urine Routine", "Thyroid Function (TSH)", "Lipid Profile", "Liver & Kidney Function Tests"],
    bookDept: "General Medicine",
    steps: [
      { title: "Book Appointment", desc: "Patient presents with fever, infection, chronic condition follow-up, or routine checkup.", icon: "📅", role: "Patient" },
      { title: "Admin Review", desc: "Admin confirms appointment. Urgent cases (high fever, acute infection) given priority slots.", icon: "🗂️", role: "Admin" },
      { title: "Consultation with General Physician", desc: "GP takes full history — vitals, temperature, BP, oxygen. Symptom analysis performed.", icon: "🩺", role: "General Physician" },
      { title: "Lab Test Request", desc: "Blood, urine, or imaging tests ordered based on clinical findings.", icon: "🔬", role: "General Physician" },
      { title: "Lab Processes & Uploads", desc: "Tests processed, results uploaded to patient record.", icon: "📋", role: "Lab" },
      { title: "Diagnosis", desc: "GP reviews results. Differential diagnosis narrowed down to final diagnosis.", icon: "📋", role: "General Physician" },
      { title: "Prescription", desc: "Antibiotics, antivirals, or chronic disease medications prescribed. Specialist referral issued if needed.", icon: "💊", role: "General Physician" },
      { title: "Pharmacy & Billing", desc: "Medicines dispensed at pharmacy. Invoice generated, insurance settled.", icon: "🧾", role: "Pharmacy / Billing" },
      { title: "Follow-Up", desc: "Review in 3–7 days for acute cases. Chronic disease patients enrolled in management programme.", icon: "📆", role: "General Physician" },
    ],
  },
  {
    slug: "laboratory",
    name: "Laboratory Services",
    tagline: "Diagnostics & Pathology",
    color: "from-indigo-500 to-blue-600",
    accentBg: "bg-indigo-50",
    accentText: "text-indigo-700",
    accentBorder: "border-indigo-200",
    conditions: ["Doctor-ordered diagnostics", "Pre-surgical screenings", "Chronic disease monitoring", "Infection & culture tests", "Hormonal panels", "Cancer marker tests"],
    specialists: ["Lab Technician", "Pathologist", "Microbiologist", "Hematologist", "Biochemist"],
    tests: ["Blood Culture", "Histopathology (Biopsy)", "Microbiology Culture", "Haematology Panel", "Clinical Chemistry Panel", "Serology / Immunology"],
    bookDept: "Laboratory Services",
    steps: [
      { title: "Doctor Orders Test", desc: "Treating physician submits lab test request via the patient's appointment record.", icon: "📝", role: "Doctor" },
      { title: "Lab Admin Receives Request", desc: "Lab management system flags the test request, assigns priority level.", icon: "🗂️", role: "Lab Admin" },
      { title: "Assign Technician", desc: "Lab admin assigns a qualified technician based on test type (haematology, microbiology, etc.).", icon: "🔬", role: "Lab Admin" },
      { title: "Sample Collection", desc: "Technician collects blood, urine, swab, tissue biopsy or other specimen from patient.", icon: "🩸", role: "Lab Technician" },
      { title: "Testing & Processing", desc: "Specimen processed using analysers, cultures incubated, microscopic examination performed.", icon: "⚗️", role: "Lab Technician" },
      { title: "Pathologist Verification", desc: "Senior pathologist reviews results, validates abnormal values, signs off on report.", icon: "✅", role: "Pathologist" },
      { title: "Report Upload", desc: "Verified report uploaded to patient record and linked to the requesting doctor's dashboard.", icon: "📤", role: "Lab Technician" },
      { title: "Doctor & Patient Notification", desc: "Doctor notified via dashboard. Patient notified on their portal. Critical values flagged urgently.", icon: "🔔", role: "System / Lab" },
    ],
  },
  {
    slug: "pharmacy",
    name: "Pharmacy",
    tagline: "Prescription Dispensing & Inventory",
    color: "from-emerald-500 to-green-600",
    accentBg: "bg-emerald-50",
    accentText: "text-emerald-700",
    accentBorder: "border-emerald-200",
    conditions: ["Prescription fulfillment", "OTC medication dispensing", "Chronic medication management", "IV preparation", "Medication counselling", "Drug interaction checks"],
    specialists: ["Pharmacist", "Clinical Pharmacist", "Pharmacy Technician", "Drug Information Specialist"],
    tests: ["Drug Interaction Check", "Contraindication Review", "Allergy Screening", "Dosage Verification", "Stock Level Audit"],
    bookDept: "Pharmacy",
    steps: [
      { title: "Doctor Issues Prescription", desc: "Digital prescription created and signed by treating doctor, linked to patient appointment.", icon: "📝", role: "Doctor" },
      { title: "Prescription Appears on Patient Portal", desc: "Patient can view their prescription, medicines, dosage and instructions on their dashboard.", icon: "📱", role: "System" },
      { title: "Medicine Order Created", desc: "Pharmacy receives the prescription order in the pharmacy queue for processing.", icon: "📋", role: "System / Patient" },
      { title: "Pharmacist Verification", desc: "Pharmacist reviews prescription for accuracy, drug interactions, contraindications and allergies.", icon: "✅", role: "Pharmacist" },
      { title: "Inventory Check", desc: "Stock levels verified. If out of stock, vendor reorder triggered or substitute suggested.", icon: "📦", role: "Pharmacist" },
      { title: "Payment", desc: "Patient pays for medicines. Insurance coverage applied where applicable. Receipt generated.", icon: "💳", role: "Billing / Patient" },
      { title: "Dispatch / Pickup", desc: "Medicines labelled, bagged with instructions. Patient picks up or hospital delivery arranged.", icon: "🏪", role: "Pharmacy Technician" },
    ],
  },
  {
    slug: "insurance",
    name: "Insurance",
    tagline: "Claims & Coverage Management",
    color: "from-blue-500 to-indigo-600",
    accentBg: "bg-blue-50",
    accentText: "text-blue-700",
    accentBorder: "border-blue-200",
    conditions: ["Inpatient hospitalisation claims", "Outpatient procedure coverage", "Emergency treatment coverage", "Chronic disease coverage", "Pre-authorisation requests", "Reimbursement claims"],
    specialists: ["Insurance Officer", "Claims Processor", "Medical Underwriter", "Pre-auth Coordinator"],
    tests: ["Policy Coverage Verification", "Medical Records Review", "Pre-authorisation", "Clinical Audit", "Settlement Calculation"],
    bookDept: "General Medicine",
    steps: [
      { title: "Patient Receives Treatment", desc: "Patient completes treatment across department(s). Full treatment record generated.", icon: "🏥", role: "Hospital" },
      { title: "Claim Request Submitted", desc: "Patient or hospital submits insurance claim with invoice, medical records, and treatment summary.", icon: "📝", role: "Patient / Billing" },
      { title: "Insurance Verification", desc: "Insurance officer verifies patient's active policy, coverage dates, and claim eligibility.", icon: "🔍", role: "Insurance Officer" },
      { title: "Coverage Validation", desc: "Policy terms reviewed — treatment covered, sub-limits checked, exclusions confirmed.", icon: "📋", role: "Medical Underwriter" },
      { title: "Hospital Approval", desc: "Hospital billing department confirms invoice accuracy and treatment necessity.", icon: "✅", role: "Hospital Admin" },
      { title: "Claim Processing", desc: "Claim approved or partially approved. Claim amount calculated after deductibles and copay.", icon: "⚙️", role: "Claims Processor" },
      { title: "Settlement", desc: "Approved amount settled directly to hospital or reimbursed to patient. EOB generated.", icon: "💸", role: "Insurance / Billing" },
    ],
  },
  {
    slug: "emergency",
    name: "Emergency / Trauma",
    tagline: "24/7 Critical & Trauma Care",
    color: "from-red-500 to-rose-600",
    accentBg: "bg-red-50",
    accentText: "text-red-700",
    accentBorder: "border-red-200",
    conditions: ["Cardiac arrest & chest pain", "Major trauma & accidents", "Stroke & neurological emergencies", "Severe allergic reactions", "Breathing difficulty", "Unconsciousness & collapse"],
    specialists: ["Emergency Physician", "Trauma Surgeon", "Critical Care Specialist", "Emergency Nurse", "Paramedic"],
    tests: ["Rapid ECG", "Blood Gas Analysis", "FAST Ultrasound", "Trauma CT Scan", "Emergency Blood Panel", "Toxicology Screen"],
    bookDept: "Emergency / Trauma",
    steps: [
      { title: "Emergency Request Raised", desc: "Patient or bystander contacts emergency helpline or walks into Emergency department.", icon: "🚨", role: "Patient / Bystander" },
      { title: "Support Team Alert", desc: "Emergency team alerted. Triage nurse assesses severity and assigns priority level (P1/P2/P3).", icon: "📡", role: "Emergency Team" },
      { title: "Nearest Hospital Search", desc: "If ambulance dispatch — nearest Medilink facility with emergency capacity identified.", icon: "🗺️", role: "Dispatch / System" },
      { title: "Bed Availability Check", desc: "Emergency bay availability checked in real-time. ICU/HDU beds reserved for critical cases.", icon: "🛏️", role: "Reception / System" },
      { title: "Hospital Confirmation & Ambulance", desc: "Ambulance dispatched or patient directed to confirmed emergency bay. ETA communicated.", icon: "🚑", role: "Dispatch / Reception" },
      { title: "Admission & Stabilisation", desc: "Patient admitted. IV access, oxygen, monitoring initiated. Life-saving interventions if needed.", icon: "🏥", role: "Emergency Physician" },
      { title: "Doctor Assignment & Treatment", desc: "Emergency physician and relevant specialist assigned. Investigations, interventions and treatment initiated.", icon: "👨‍⚕️", role: "Emergency Doctor" },
      { title: "ICU / Ward Transfer or Discharge", desc: "Stable patients transferred to ward or ICU. Discharge with detailed instructions for minor cases.", icon: "🔄", role: "Emergency Team" },
    ],
  },
];

export function getWorkflow(slug: string): DeptWorkflow | undefined {
  return workflows.find(w => w.slug === slug);
}

export const deptSlugMap: Record<string, string> = {
  "Cardiology":            "cardiology",
  "Neurology":             "neurology",
  "Orthopedics":           "orthopedics",
  "Pediatrics":            "pediatrics",
  "Emergency / Trauma":    "emergency",
  "General Medicine":      "general-medicine",
  "Laboratory Services":   "laboratory",
  "Pharmacy":              "pharmacy",
  "Oncology":              "general-medicine",
  "Radiology":             "laboratory",
  "Gynecology / Obstetrics": "general-medicine",
};
